### ISSUE TITLE
stone_sdk.validation e stone_sdk.deviceSelected não estão retornando callback

### ISSUE THREAD

**Issue by jgabrielfaria** [stone-pagamentos/plugin-cordova#3]
As chamadas stone_sdk.validation e stone_sdk.deviceSelected não estão retornando callback.

Exemplo: 

```
stone_sdk.deviceSelected(device, function() {
      $scope.selectedDevice = device;
      console.log('\nLOG Pareado com sucesso!\n');
    }, function() {
      console.log('\nLOG Erro ao Parear!\n');
    });
```

O device é pareado (o aparelho mPOS reconhece a conexão e a tela do App mostra o pareamento) porém nenhum dos callbacks é chamado.

**Comment by jgabrielfaria** [comment]
@victormendes5  coloquei a Issue aqui no git pra gente ir discutindo.

**Comment by victormendes5** [comment]
@jgabrielfaria Eu vi aqui o erro, eu subi um comando errado na documentação.

Na instalação do plugin, use este comando: 

    $ ionic plugin add https://github.com/stone-pagamentos/plugin-cordova.git

**Comment by jgabrielfaria** [comment]
@victormendes5 eu já estava instalando desse modo na verdade.

De qualquer maneira, desinstalei e instalei novamente o plugin e continuo sem o callbacks.

Se você testar por ai:

```
stone_sdk.deviceSelected(device, function() {
  $scope.selectedDevice = device;
  console.log('\nLOG Pareado com sucesso!\n');
}, function() {
  console.log('\nLOG Erro ao Parear!\n');
});

console.log('testando');
```

o único log que vai aparecer vai ser o `testando`.

**Comment by jgabrielfaria** [comment]
e na tela do App aparecem as mensagens:

"Criando conexão com o pinpad selecionado"

e depois:

"pinpad conectado"

**Comment by victormendes5** [comment]
Vc usa o Ionic 1 ou 2?

**Comment by jgabrielfaria** [comment]
@victormendes5 nesse projeto estamos com Ionic 1

**Comment by jgabrielfaria** [comment]
@victorfontes mentira! Me enganei! Estamos com ionic 2! v 2.2.1
